### ISSUE TITLE
기능 목록 도출

### ISSUE THREAD

**Issue by mingd1023** [PoolC/poolc-renewal-back#1]
## 🗣 설명

구현할 기능 목록 도출

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 세미나 관련 기능 포함
2. 프로젝트 참여 인원 관리 기능 포함
3. 투표 기능 삭제,,ㅠㅠ

**Comment by yoonseokch** [comment]
3번은 유지가 어려워서 삭제를 원하시는건가요? 아니면 카카오톡이 있어서 안하시는건가요
