### ISSUE TITLE
Domain TestCase 코드 작성

### ISSUE THREAD

**Issue by hcpak** [PoolC/poolc-renewal-back#15]
## 🗣 설명
작성한 Domain이 제대로 동작하는 지 확인하기 위해 TestCase 코드를 작성해야 한다. 

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 연관 관계가 있는 도메인을 삭제할 시 cascade가 잘 작동하는 지 확인한다.

**Comment by yoonseokch** [comment]
삭제 확인하였습니다
