### ISSUE TITLE
Repository 전달인자 수정

### ISSUE THREAD

**Issue by hcpak** [PoolC/poolc-renewal-back#51]
## 🗣 설명
Repository 전달인자가 뒤죽박죽으로 되어 있기 때문에, save 메소드를 제외한 나머지는 객체로 전달인자 받지 않도록 바꾼다. 
## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. BoardRepository delete문 전달인자 수정
2. BookRepository delete문 추가
3. MemberRepository delete문 전달인자 수정
4. PostRepository findAllByBoard문 전달인자 수정, findAllByAuthor문 전달인자 수정
5. ProjectRepository delete문 추가

**Comment by yoonseokch** [comment]
id값으로 다하자는 말씀이시죠?
