### ISSUE TITLE
PostgreSQL 연동

### ISSUE THREAD

**Issue by hcpak** [PoolC/poolc-renewal-back#8]
## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 기존에 있던 PostgreSQL 연동

**Comment by mingd1023** [comment]
바로 기존 db랑 연동하면 위험할 것 같아서..귀찮더라도 mysql 올렸던 서버에 postgreSQL 도 하나 올려서 개발하는 동안에는 거기로 연결해서 쓰는 게 좋을 것 같아요~!

**Comment by yoonseokch** [comment]
알겠습니당

**Comment by hcpak** [comment]
mysql 올렸던 서버에 postgreSQL 설치했고 연동확인 완료했습니다.
